---
- name: replacing lines 
  hosts: planetexpress

  vars:
          - fileloc: "/var/log/bootstrap.log"

  tasks:
          - name: "replace a line into {{ fileloc }}"
            replace:
                    path: "{{ fileloc }}"
                    regexp: "^Setting up lib.*"
                    replace: "REDACTED BY ANSIBLE replace module"
                    backup: yes

            become: yes
